import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{Activity,ArrowUpRight,BookOpen,Check,ChevronRight,Database,Eye,FileClock,Menu,Radio,ShieldCheck,Wallet,X,Zap}from'lucide-react';import'./styles.css';
const markets=[{q:'Will City Alpha publish its audited accessibility report before Oct 1?',phase:'EVIDENCE',yes:68,no:32,n:142,color:'lime'},{q:'Will the regional grid exceed 60% renewable generation this quarter?',phase:'REVEAL',yes:74,no:26,n:89,color:'amber'},{q:'Will the open transit API reach 99.95% monthly uptime?',phase:'COMMIT',yes:55,no:45,n:217,color:'coral'}];
function Count({to}){const[n,setN]=useState(0);useEffect(()=>{let i=0;const id=setInterval(()=>{i+=2;setN(Math.min(i,to));if(i>=to)clearInterval(id)},18);return()=>clearInterval(id)},[to]);return n}
function App(){const[wallet,setWallet]=useState('');const[active,setActive]=useState(0);const[toast,setToast]=useState('');const[menu,setMenu]=useState(false);const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2800)};const connect=async()=>{try{const a=await window.ethereum?.request({method:'eth_requestAccounts'});a?.[0]?setWallet(a[0]):notify('No browser wallet detected.')}catch{notify('Connection declined.')}};return <div className="app"><header><a className="brand" href="#"><span><Activity/></span><b>FORECAST<span>FORGE</span></b><small>Evidence, not odds.</small></a><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}><a href="#markets">Markets</a><a href="#resolution">Resolution</a><a href="#profile">Reputation</a><span className="live"><i/>STUDIONET LIVE</span><button onClick={connect}><Wallet/>{wallet?wallet.slice(0,6)+'...'+wallet.slice(-4):'CONNECT'}</button></nav></header><main>
<section className="ticker"><span>NETWORK 61999</span><span>MARKETS <b><Count to={24}/></b></span><span>SEALED FORECASTS <b><Count to={387}/></b></span><span>RESOLUTION TOLERANCE <b>±10</b></span><span>STATUS <b className="green">OPERATIONAL</b></span></section>
<section className="hero"><div><div className="kicker"><Radio/> LIVE RESEARCH TERMINAL</div><h1>Forecast first.<br/><em>Prove it later.</em></h1><p>Commit a private forecast, reveal it without revision, and let GenLayer validators resolve the result from timestamped evidence snapshots.</p><div className="actions"><button className="primary" onClick={()=>notify('Market creation panel ready.')}>OPEN A MARKET <ArrowUpRight/></button><a href="#resolution">HOW RESOLUTION WORKS <ChevronRight/></a></div></div><div className="signal"><div className="orb"><Activity/></div><span>VALIDATOR SIGNAL</span><strong><Count to={94}/>%</strong><small>agreement · last resolution</small></div></section>
<section id="markets" className="section-head"><div><span>01 / ACTIVE MARKETS</span><h2>Signals under review</h2></div><div className="tabs">{['ALL','COMMIT','REVEAL','EVIDENCE'].map((x,i)=><button className={active===i?'active':''} onClick={()=>setActive(i)} key={x}>{x}</button>)}</div></section>
<section className="market-grid">{markets.filter(m=>active===0||m.phase===['','COMMIT','REVEAL','EVIDENCE'][active]).map((m,i)=><article className={'market '+m.color} key={m.q}><div className="sweep"/><div className="market-top"><span>FF-{String(240+i).padStart(3,'0')}</span><b><i/>{m.phase}</b></div><h3>{m.q}</h3><div className="prob"><span style={{width:m.yes+'%'}}/><div><b><Count to={m.yes}/>% YES</b><b>{m.no}% NO</b></div></div><footer><span><Eye/>{m.n} sealed</span><span><FileClock/>closes 18h</span><button onClick={()=>notify('Public dossier opened.')}>OPEN <ChevronRight/></button></footer></article>)}</section>
<section id="resolution" className="resolution"><div className="section-head"><div><span>02 / RESOLUTION ENGINE</span><h2>Facts enter through snapshots</h2></div><p>Raw URLs are not enough. Every submission carries a content hash, retrieval time, and optional archive.</p></div><div className="flow">{[[Database,'01','SNAPSHOT','HTTPS source + SHA-256'],[ShieldCheck,'02','CONSENSUS','Same outcome, confidence ±10'],[Zap,'03','APPEAL','One new-evidence review'],[Check,'04','FINAL','Portable accuracy updated']].map(([Icon,n,t,d])=><div key={n}><span>{n}</span><Icon/><b>{t}</b><small>{d}</small></div>)}</div></section>
<section id="profile" className="profile"><div><span className="label">PUBLIC FORECASTER PROFILE</span><h2>Accuracy that travels.</h2><p>Resolved and correct counts live on-chain. UNRESOLVED markets remain neutral, so ambiguous evidence never damages a forecaster.</p></div><div className="profile-card"><div className="avatar">0X</div><div><small>DEMO FORECASTER</small><b>0x7A41...09E2</b></div><strong><Count to={81}/><small>% ACCURACY</small></strong><div className="stats"><span><b>42</b>RESOLVED</span><span><b>34</b>CORRECT</span><span><b>8</b>INCORRECT</span></div></div></section>
</main><footer className="sitefoot"><b>FORECASTFORGE</b><span>Commit-reveal · Evidence snapshots · Neutral unresolved · One appeal</span><a href="https://explorer-studio.genlayer.com/address/0x92993B6F786BdE15e62DFD3669f2822A45B3d11f" target="_blank" rel="noreferrer">VERIFIED ON GENLAYER</a></footer>{toast&&<div className="toast"><Activity/>{toast}</div>}</div>};createRoot(document.getElementById('root')).render(<App/>);
